version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."

  pre_build:
    commands:
      - echo "Nothing to do in pre_build phase for static HTML/CSS"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running build steps for static website (if any)..."

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Preparing artifacts for deployment"

artifacts:
  files:
    - '**/*'
  base-directory: '.'  # Use '.' if files are in root
