version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Optional; only if you plan to use npm tools like minifiers
    commands:
      - echo "Installing dependencies (if any)..."

  pre_build:
    commands:
      - echo "Nothing to do in pre_build phase for static HTML/CSS"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running build steps for static website (if any)..."
      # Example: Minify HTML/CSS using a tool like clean-css-cli or html-minifier (optional)

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Preparing artifacts for deployment"

artifacts:
  files:
    - '**/*'
  base-directory: 'public' # Change this to your build output directory or root folder if applicable
